#cloud-config
package_upgrade: true
packages: [python3-pip, python3-venv, python3.10-venv, git, curl]
users:
- name: pjds
  ssh_import_id:
  - gh:VariableDeclared
- name: fleet-agent
  sudo: "fleet-agent ALL=(ALL) NOPASSWD: /usr/bin/apt-get update, /usr/bin/apt-get dist-upgrade -y, /usr/bin/dnf check-update, /usr/bin/dnf upgrade -y"
  lock_passwd: true
  
write_files:
  - path: /etc/systemd/system/fleet-agent.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Linux Fleet Agent
      [Service]
      User=root
      WorkingDirectory=/opt/fleet-agent/fleet_manager
      Environment="AGENT_SECRET_KEY=super-secret-fleet-key-123"
      ExecStart=/opt/fleet-agent/fleet_manager/venv/bin/uvicorn agent.agent:app --host 0.0.0.0 --port 8080
      Restart=always
      User=fleet-agent
      [Install]
      WantedBy=multi-user.target

runcmd:
  - mkdir -p /opt/fleet-agent && cd /opt/fleet-agent
  - git clone https://github.com/VariableDeclared/fleet_manager.git
  - cd fleet_manager
  - python3 -m venv venv
  - /opt/fleet-agent/fleet_manager/venv/bin/pip install -r agent/requirements.txt
  - systemctl daemon-reload
  - systemctl enable fleet-agent --now
